### ISSUE TITLE
Option to reset autocomplete

### ISSUE THREAD

**Issue by supertrip86** [dudyn5ky1/select-pure#10]
Is there any option to clear all the selected values and reset the autocomplete span to default?
Or should I just create a new instance of SelectPure and/or clear the array of values and the elements inside the span?

**Comment by dudyn5ky1** [comment]
@supertrip86 sounds like an easy feature. Will include that in the next version

**Comment by supertrip86** [comment]
Thanks, in the meantime I'll just drop a few lines of code to handle this feature myself.

**Comment by dudyn5ky1** [comment]
Added in version `0.5.0`.
