### ISSUE TITLE
Maintain the dropdown list openned

### ISSUE THREAD

**Issue by jvegaseg** [dudyn5ky1/select-pure#14]
Is there any way to maintain the dropdown list openned when you select an option?

If you have to choose many options, it is better to left the dropdown openned to click directly in every option without to click in the label.

**Comment by dudyn5ky1** [comment]
True, will be added with the next release.

**Comment by ejayfl** [comment]
When is the next release?

**Comment by dudyn5ky1** [comment]
@ejayfl don't have too much time lately. Feel free to make a PR, if you want this feature.

**Comment by dudyn5ky1** [comment]
This is how `multiple` select behaves now since `2.0.1` version.
