### ISSUE TITLE
Disabled attribute not disabling option

### ISSUE THREAD

**Issue by beck24** [dudyn5ky1/select-pure#17]
I'm using this as a multiselect and need a couple of the options disabled in a certain cases.

My usage looks like this:

    this.instance = new SelectPure(this.renderNode, {
      options: this.options,
      multiple: true,
      value: this.value,
      onChange: () => this.valueChanged(),
      inlineIcon: this.closeIcon
    });

My options array looks like:

    [
    {
      label: 'Option 1',
      value: 'option_1',
      disabled: true
    },
    {
      label: 'Option 2',
      value: 'option_2',
      disabled: true
    },
    {
      label: 'Option 3',
      value: 'option_3'
    },
    {
      label: 'Option 4',
      value: 'option_4'
    },
    {
      label: 'Option 5',
      value: 'option_5'
    }
    ]

With this setup I would expect that Option 1 and Option 2 are not-selectable, but in reality they are selectable.

**Comment by dudyn5ky1** [comment]
Fixed in `0.6.0-alpha.0`.
