### ISSUE TITLE
Cannot read property 'value' of undefined if the values of the option/value array are integers

### ISSUE THREAD

**Issue by leoman** [dudyn5ky1/select-pure#18]
As the title says, the selection fails on the following line:

`var optionNode = _this2._options.find(function (_option) {
            return _option.get().getAttribute("data-value") === option.value.toString();
          });`

where option is undefined, I assume because the value was set as an integer.

Please see pen, and obseve the console when you add a new item:

https://codepen.io/leoman1/pen/XWbGvVb

**Comment by ErShakirAnsari** [comment]
Facing same issue

**Comment by Alxtaz** [comment]
Change **"value" as a string** instead of integer and it will work:

`const myOptions = [
  {
    label: "New York",
    value: "1",
  },{
    label: "Washington",
    value: "2",
  }]`

AND

`new SelectPure(".example", {
    options: myOptions,
    multiple: true,
    value: ["1", "2"]
});`

**Comment by dudyn5ky1** [comment]
Should not be happenning in `2.0.0` and further versions.
