### ISSUE TITLE
How does it work as a select for a form?

### ISSUE THREAD

**Issue by CodeCurosity** [dudyn5ky1/select-pure#19]
Awesome job with this but how does it work as a form control, i only see spans and divs, no name attribute to pass the values on form submission?

**Comment by dudyn5ky1** [comment]
Unfortunately, not implemented yet. But a good point, should have some OOB integration with the form.

**Comment by CodeCurosity** [comment]
darn it, i so wanted to integrate this in my application but i will try this myself, keep up the great work :-)

**Comment by dudyn5ky1** [comment]
@CodeCurosity PRs are always welcome :)

**Comment by stkol76** [comment]
Hi @dudyn5ky1 and @CodeCurosity  was this ever fixed, or found a solution for this? :-) .. I am using SelectPure (awsome script @dudyn5ky1 ) on my web app but is stock on not getting the selected values passed with the forms, so any help would be greately appriciated :-)

**Comment by ukropf** [comment]
`            onChange: value => {
                //console.log(value),
                //value.forEach(element => document.getElementById('rooms').getElementsByTagName('option')[element].selected = 'selected');
                value.forEach(element => document.querySelectorAll('#rooms option[value="'+element+'"]')[0].setAttribute("selected", "selected"));

                }`

**Comment by dudyn5ky1** [comment]
`2.0.0` supports `<form>` now (inserting a hidden input and changing it's values on value select).
