### ISSUE TITLE
Cannot find "/dist/bundle.min.js" in select-pure@2.0.0-alpha.6

### ISSUE THREAD

**Issue by Devarshi87** [dudyn5ky1/select-pure#36]
Cannot find "/dist/bundle.min.js" in select-pure@2.0.0-alpha.6

**Comment by dudyn5ky1** [comment]
Hello @Devarshi87 ,

README for 2.0.0+ is currently [here](https://github.com/dudyn5ky1/select-pure/blob/V2-main/README.md).

If you want to use an older version, please refer to the latest stable `0.6.2` version.

Thanks!
