### ISSUE TITLE
multiple=false without initial selection

### ISSUE THREAD

**Issue by sookoll** [dudyn5ky1/select-pure#5]
There is no possibility to init without selection. Null will select first option. If I try to go around and add first option as
```
{ label: 'Select here', value: '' }
```
then it throws error. Adding some stupid 'null' to value, fix it for me, but it is hack that I do not to wrote into code.

**Comment by dudyn5ky1** [comment]
Added option to add placeholder, thus selecting option by default is not needed anymore.
