### ISSUE TITLE
Height of options not adapting to content

### ISSUE THREAD

**Issue by tmharryfrancis** [dudyn5ky1/select-pure#51]
Hey,

So it looks like the height variable (set with `--select-height`) is applying to both the select and the options within it. This means if the content of an option is longer than the height/width area, it get's cut off.

I'd expect this to be min-height for options, allowing it to adapt to content.

Alternatively, if you could let me know if there is another way to do this that would be great as I am having no luck styling shadow root elements.

Thanks, Harry.

**Comment by tmharryfrancis** [comment]
Any thoughts?

**Comment by tmharryfrancis** [comment]
Hey @dudyn5ky1,

Sorry for the delay, I've never done a PR before but decided it was time! See: https://github.com/dudyn5ky1/select-pure/pull/56

Let me know if I have done anything incorrectly.

**Comment by dudyn5ky1** [comment]
The issue should be available since the version `2.1.4`.
