### ISSUE TITLE
Allow cancel icon to be a completely different element (not fontawesome)

### ISSUE THREAD

**Issue by titonova** [dudyn5ky1/select-pure#55]
Currently, the method for adding  option for including a cancel icon on each selected option is
```
{
icon: "far fa-times"
}
```

But, that assumes that the site is using fontawesome. Meaning if I want to use the select-pure library, I'd have to download the entire fontawesome file to my page for just a single icon. It seems a bit over kill.

I propose to change the option to something like this:

```
{
icon: "<i class='far fa-times'></i>"
}
```
So that, we can use whatever we choose as the icon, including an SVG, PNG or  even just a letter.

Thanks

**Comment by dudyn5ky1** [comment]
Hi @titonova ,

I think you are referring to the old version of the component. Please take a look at the newest README for more details.
