### ISSUE TITLE
Cannot read property 'value' of undefined.

### ISSUE THREAD

**Issue by danhadv** [dudyn5ky1/select-pure#7]
Just downloaded this component.  Exactly what I'm looking for seems very easy to use!  However, I'm running into the following javascript error when selecting an item in the drop down.

```
Uncaught TypeError: Cannot read property 'value' of undefined
    at eval (index.js:180)
    at Array.find (<anonymous>)
    at eval (index.js:179)
    at Array.map (<anonymous>)
    at SelectPure._setValue (index.js:175)
    at SelectPure._handleClick (index.js:132)
eval @ index.js:180
eval @ index.js:179
_setValue @ index.js:175
_handleClick @ index.js:132
```
Source of Error

```
          var optionNode = _this2._options.find(function (_option) {
            return _option.get().getAttribute("data-value") === option.value.toString();
          });
```
Here is my Config:

```
                 this.ddAdmin = new SelectPure( '#dd-board-admin', {
                    options: opts,
                    multiple: true,
                    autocomplete: true,
                    value: [],
                    onChange: value => { console.log( value );}
                } );

```

Any thoughts?  Don't want to give up on this control, but don't have much time to figure out before I have to push forward with another solution.

Dan

**Comment by dudyn5ky1** [comment]
Hi @danhadv.

It would be helpful if you post your opts array as well.

**Comment by dudyn5ky1** [comment]
Just by looking at your code, seems like the opts is undefined, or an empty array.

**Comment by danhadv** [comment]
Thanks for getting back to me.  And yes you are on the right track.  I "map"ped my opts array from a dataset where the value was an integer not a string.  Changed the value to a string in my map function ( the one that I pass into opts) and everything works fine now.
