### ISSUE TITLE
consume as ES6 module

### ISSUE THREAD

**Issue by zevero** [dudyn5ky1/select-pure#9]
I am confused. On github src/index.js last line reads  `export default SelectPure;`
so doing
`import SelectPure from "path/to/src/index.js";`
works
But after `npm i` there is no src folder in my node_modules dir. Instead I find dist/bundle.min.js for normal script tags and I find lib/index.js presumably for usage in node.js, since last line happens to be `exports.default = SelectPure;`

On both I get an export not found error when trying to import it as an ES6 module. Please provide a version for ES6 import. Thank you!

**Comment by dudyn5ky1** [comment]
@zevero 
Does the following work for you?

`import SelectPure from "select-pure";`

**Comment by dudyn5ky1** [comment]
Alternatively, if don't like absolute path:
`import SelectPure from 'path/node_modules/select-pure/lib/index.js';`
